server:
  port: ${LOGS_API_PORT:8080}

# Production logging configuration (patterns inherited from base)
logging:
  level:
    com.homeassistant: ${WARN_LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.springframework.security: WARN
    software.amazon.awssdk: WARN
    root: WARN

# AWS Configuration is inherited from application.yml base file 