spring:
  application:
    name: logs-api
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}

# Common logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 

# AWS Configuration - available in all profiles
aws:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  sns:
    topic:
      arn: ${AWS_SNS_TOPIC_ARN}

# Duplicate Filter Configuration
duplicate-filter:
  enabled: ${DUPLICATE_FILTER_ENABLED:true}
  ttl-minutes: ${DUPLICATE_FILTER_TTL_MINUTES:5}
  cleanup-interval-minutes: ${DUPLICATE_FILTER_CLEANUP_INTERVAL_MINUTES:10}
  max-cache-size: ${DUPLICATE_FILTER_MAX_CACHE_SIZE:1000}

# Retry Policy Configuration
retry-policy:
  enabled: ${RETRY_POLICY_ENABLED:true}
  max-attempts: ${RETRY_POLICY_MAX_ATTEMPTS:3}
  initial-delay-seconds: ${RETRY_POLICY_INITIAL_DELAY_SECONDS:1}
  backoff-multiplier: ${RETRY_POLICY_BACKOFF_MULTIPLIER:2.0}
  execution-interval-seconds: ${RETRY_POLICY_EXECUTION_INTERVAL_SECONDS:30}
  cleanup-interval-minutes: ${RETRY_POLICY_CLEANUP_INTERVAL_MINUTES:60}